### ISSUE TITLE
Error in running test module

### ISSUE THREAD

**Issue by m-zakeri** [Marchetz/MANTRA-CVPR20#7]
Hi,
I get the following error when running the `test.py` module: 

RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR

I use Python 3.6 with all requirements in the `requirement.txt`.

**Comment by m-zakeri** [comment]
> Hi, I get the following error when running the `test.py` module:
> 
> RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
> 
> I use Python 3.6 with all requirements in the `requirement.txt`.


After using coda 10.1 I got the following error:

torch.nn.modules.module.ModuleAttributeError: 'GRU' object has no attribute '_flat_weights_names'

Can you please specify the exact version of CUDA which the code can be executed on?

**Comment by fedebecat** [comment]
Hi,

which version of pytorch are you using? This error should be related to the torch version being higher than 1.3.1.
Try downgrading to 1.3.1 if you are not using it already.

As for cuda if I am not mistaken you should be able to run everything smoothly with cuda 9.2.

Federico

**Comment by m-zakeri** [comment]
I

> Hi,
> 
> which version of pytorch are you using? This error should be related to the torch version being higher than 1.3.1. Try downgrading to 1.3.1 if you are not using it already.
> 
> As for cuda if I am not mistaken you should be able to run everything smoothly with cuda 9.2.
> 
> Federico

Thanks. I tried PyTorch 1.3.1 on Ubuntu 20.04, but the error remains. 
After switching to Ubuntu 18.04, I could run the code successfully even with Cuda 11.9. 
Here is my config, which works correctly with pre-trained models:
* Ubuntu 18.04,
* Python 3.6,
* Cuda 11.7
